# Generated by Django 6.0.3 on 2026-04-19 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0003_order_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
    ]
